### ISSUE TITLE
skyfi.py doesn't set mode

### ISSUE THREAD

**Issue by bircoe** [kabongsteve/HomeAssistant#1]
Hi, I was stoked to find this module, but unfortunately the one thing it doesn't do to make it useful for automation is set the operation mode, available modes are:
1 = Auto
2 = Heat
3 = Heat/Auto
4 = Dry
8 = Cool
9 = Cool/Auto
16 = Fan

Setting to heat mode would be done by passing m=2 in the set.cgi string but the code currently doesn't do that:
line 158: 
`payload = "/set.cgi?pass={}&p={}&t={:.5f}&f={}".format(self._password, pstate, self._target_temperature, fan)
`
I don't know enough about Python to resolve this, I assume there will need to be a function that substitutes the string for the corresponding value, ie Heat = 2.

**Comment by kabongsteve** [comment]
Sorry, I missed this.

I have done a few fixes and enhancements, including what you are talking about, just not uploaded.

Will do that shortly.
Steve

**Comment by bircoe** [comment]
I managed to get it updated and applied the fixes required for the recent supported_features change.

https://github.com/bircoe/HomeAssistant/blob/master/climate/skyfi.py

When I got some spare time next I was going to update the operation list and fan list arrays similar to lines 67/68 on this:
https://github.com/robhuls/home-assistant/blob/dev/homeassistant/components/climate/daikin.py

**Comment by kabongsteve** [comment]
I believe this is all fixed in latest release
